- tensorflow-serving/0000-tensorflow_patches.patch
- tensorflow-serving/build.sh
https://github.com/open-ce/open-ce/issues/4.
Additionally this commit includes changes for cuda_compute_capabilities that are supported for both on ppc64le and x86.
> Fixed memcpy linking issue on x86

- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
Fixes https://github.com/open-ce/tensorflow-serving-feedstock/issues/6.
> Switched from cudatoolkit-dev to local cuda installation

- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
Fixes build failure on baremetal.
> Fixed build on baremetal

- .github/workflows/feedstock-pr.yml
- buildscripts/set_python_path_for_bazelrc.sh
- buildscripts/set_tf_serving_bazelrc.sh
- buildscripts/set_tf_serving_nvidia_bazelrc.sh
- tensorflow-serving-api/build.sh
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-tensorflow_patches.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.
> Tensorflow serving update to 2.4

- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-tensorflow_patches.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/meta.yaml
Fixes https://github.com/open-ce/open-ce/issues/226
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.
> Updated to TF serving 2.4.0 final tag

- buildscripts/set_python_path_for_bazelrc.sh
- buildscripts/set_tf_serving_bazelrc.sh
- buildscripts/set_tf_serving_nvidia_bazelrc.sh
- tensorflow-serving-api/build.sh
- tensorflow-serving/build.sh
Fixes https://github.com/open-ce/open-ce/issues/258.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.
> Updated copyright information

- tensorflow-serving-api/meta.yaml
Let's specify the build string here on noarch packages since the default strings differ when built on different architectures. This will help when automation combines multiple different output directories (from different arches for example) into a single channel without having duplicates.
> Update build string

- tensorflow-serving-api/meta.yaml
- tensorflow-serving/meta.yaml
Add the protobuf version to the build string, along with the PKG_HASH value.
> Add protobuf version to the build string

- tensorflow-serving-api/meta.yaml
- tensorflow-serving/meta.yaml
Anaconda just updated toolchains and associated libraries.
This PR forces this recipe to build using the older toolchain and libraries by using the pins created in:
open-ce/open-ce#431
open-ce/open-ce#431
Issue:
open-ce/open-ce#315
> pin gcc libs

- buildscripts/set_tf_serving_nvidia_bazelrc.sh
- config/conda_build_config.yaml
- tensorflow-serving-api/0001-Replace-k8-with-ppc-for-Power-builds.patch
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000a-TF-Build-fix-x86-64.patch
- tensorflow-serving/0000b-Fix-plus-memcpy-patch.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
Refreshes TF serving to 2.5.1.
> 250 update

- tensorflow-serving/meta.yaml
Fixes validation failure on ppc with cuda 10.2.
> Fixed filters which was causing validation failure on ppc

- tensorflow-serving-api/meta.yaml
- tensorflow-serving/meta.yaml
Adjust libgcc and libstdc++ runtime dependencies for xgboost
open-ce/open-ce#452
> Remove libgcc runtime pins

- buildscripts/set_tf_serving_nvidia_bazelrc.sh
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
Disable TensorRT for 1.3 release.
> Disable TRT temporarily for 1.3

- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-TF-Build-fix-x86-64.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/meta.yaml
Updated TF serving to the 2.6.2 tag.
> Updated TF serving to 2.6.2

- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-TF-Build-fix-x86-64.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
> 270 update

- buildscripts/set_tf_serving_bazelrc.sh
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
> Updated recipe to support P10 builds

- buildscripts/set_tf_serving_bazelrc.sh
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
Porting 1.5.3 changes back to main.
> Rebase 153

- buildscripts/set_tf_serving_bazelrc.sh
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-TF-Build-fix-x86-64.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/meta.yaml
> 280 update

- tensorflow-serving/meta.yaml
> Py 3.10 support added

- tensorflow-serving-api/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-TF-Build-fix-x86-64.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/meta.yaml
> Updated to 2.9.2

- tensorflow-serving-api/0001-Replace-k8-with-ppc-for-Power-builds.patch
- tensorflow-serving-api/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-TF-Build-fix-x86-64.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/meta.yaml
> Refreshed to 2.10

- tensorflow-serving-api/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0000-TF-Build-fix-x86-64.patch
- tensorflow-serving/0001-TF-Build-fix-ppc64le.patch
- tensorflow-serving/meta.yaml
> TF serving updated to 2.9.3

- tensorflow-serving-api/build.sh
- tensorflow-serving/build.sh
> Call common function for bazel cleanup

- tensorflow-serving-api/meta.yaml
- tensorflow-serving/meta.yaml
> Updated protobuf pin

- tensorflow-serving/meta.yaml
Tensorflow serving has its own libevent config - https://github.com/tensorflow/serving/blob/2.12.1/tensorflow_serving/workspace.bzl#L38. So removed it from dependencies. 
> remove libevent dependency

- buildscripts/set_tf_serving_bazelrc.sh
- tensorflow-serving-api/0001-TF-Build-fixed.patch
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0001-TF-Build-fixed.patch
- tensorflow-serving/meta.yaml
> 2.13 update

- buildscripts/set_tf_serving_bazelrc.sh
- tensorflow-serving-api/build.sh
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
> Suppressed Wno-array-bounds and Wno-stringop-overflow flags

- tensorflow-serving-api/build.sh
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
> Changes for gcc-toolset-12

- buildscripts/set_tf_serving_bazelrc.sh
- tensorflow-serving-api/0001-TF-patch-for-ppc64le.patch
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0001-TF-patch-for-ppc64le.patch
- tensorflow-serving/meta.yaml
> Added patch for ppc64le

- buildscripts/set_python_path_for_bazelrc.sh
- buildscripts/set_tf_serving_bazelrc.sh
- tensorflow-serving-api/0001-Replaced-k8-with-s390x.patch
- tensorflow-serving-api/0001-Updated-rules_python-to-v0.26.patch
- tensorflow-serving-api/meta.yaml
- tensorflow-serving/0001-Disabled-mavx-and-msse4.2-for-s390x.patch
- tensorflow-serving/0001-Updated-rules_python-to-v0.26.patch
- tensorflow-serving/0001-serving-patch-for-s390x.patch
- tensorflow-serving/build.sh
- tensorflow-serving/meta.yaml
> TF Serving workaround for s390x
